# Generated by Django 5.2.12 on 2026-04-07 21:44

import back_agridecis.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', validators=[back_agridecis.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('agronome', 'Agronome'), ('agriculteur', 'Agriculteur')], max_length=20, null=True, validators=[back_agridecis.validators.validate_role]),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, help_text='Format: +221 77 123 45 67 ou 771234567', max_length=20, null=True, validators=[back_agridecis.validators.validate_phone_number]),
        ),
    ]
