# Generated by Django 5.2.12 on 2026-04-07 21:46

import back_agridecis.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant IA')], max_length=20)),
                ('content', models.TextField()),
                ('audio_file', models.FileField(blank=True, help_text='Fichier audio pour les messages vocaux', null=True, upload_to='chat_audio/', validators=[back_agridecis.validators.validate_audio_file])),
                ('transcription', models.TextField(blank=True, help_text='Transcription du message audio', null=True)),
                ('message_type', models.CharField(default='text', help_text='Type de message: text, audio', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message de chat',
                'verbose_name_plural': 'Messages de chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nouvelle conversation', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('messages', models.ManyToManyField(related_name='sessions', to='ai.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de chat',
                'verbose_name_plural': 'Sessions de chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diagnosis_images/', validators=[back_agridecis.validators.validate_image_file])),
                ('culture', models.CharField(help_text='Type de culture (ex: tomate, maïs)', max_length=255, validators=[back_agridecis.validators.validate_culture_type])),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('result_json', models.JSONField(blank=True, default=dict, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('detected_disease', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requête de diagnostic',
                'verbose_name_plural': 'Requêtes de diagnostic',
                'ordering': ['-created_at'],
            },
        ),
    ]
